{% set version = "0.3.5" %}


package:
  name: lue
  version: {{ version }}


source:
  url: https://pcraster.geo.uu.nl/pcraster/packages/src/lue-{{ version }}.tar.bz2
  sha256: fc82be56ac5269b242a141a9d36aec86cdd3a8f4a5290a21e41ac5b2f543ad8b


build:
  number: 0
  skip: true  # [win and py==37]
  script_env:
    - TMPDIR                                       # [win]


requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - numpy >1.17                            # [build_platform != target_platform]
    - pybind11                               # [build_platform != target_platform]
    - {{ compiler('cxx') }}
    - make                                         # [unix]
    - git
    - conan
    - cmake
    - ninja

  host:
    - python
    - numpy >1.17
    - boost-cpp
    - hdf5
    - libgdal
    - pybind11
    - fmt
    - docopt.cpp
    - nlohmann_json
    - libhwloc
    - gperftools                                   # [not win]
    - asio

  run:
    - python
    - {{ pin_compatible('numpy') }}
    - hdf5
    - libgdal
    - fmt
    - docopt.cpp
    - gperftools                                   # [not win]


test:
  commands:
    - lue_translate -h                             # [not win]
    - lue_validate -h                              # [not win]


about:
  home: https://lue.computationalgeography.org/
  license: MIT
  license_file: LICENSE.txt
  summary: LUE scientific database and environmental modelling framework.
  description: |
    LUE is software for storing and manipulating large amounts of information
    for large amounts of objects. This information can optionally have a
    reference in time and space. For example, LUE can represent collections of
    wandering animals and their properties, some of which are changing through
    time, or the elevation of the surface of one or multiple areas. The software
    is useful, and currently mainly used, in the context of environmental
    modelling of biological and physical systems, represented by agents and
    fields, but we make sure that the software is as generic as possible,
    allowing it to be useful in other contexts as well.

    Currently, LUE contains two main parts: *LUE data model* and *LUE
    framework*. LUE data model is an implementation of the LUE physical data
    model, which allows users to perform I/O to the "LUE Scientific Database".
    It allows for the storage of large amounts of objects and their location
    in time and space, and their properties.

    LUE framework is a collection of data types and algorithms that can be
    combined to translate large amounts of information. It allows computations
    to be performed on hardware ranging from laptops to compute clusters,
    without the user having to know about high-performance computing and
    the related technology.
  doc_url: https://lue.computationalgeography.org/doc/
  dev_url: https://github.com/computationalgeography/lue/


extra:
  recipe-maintainers:
    - OliverSchmitz
    - kordejong
