{% set version = "0.3.1" %}


package:
  name: lue
  version: {{ version }}


source:
  url: http://pcraster.geo.uu.nl/pcraster/packages/src/lue-{{ version }}.tar.bz2
  sha256: b2127faf9423c8c630fbd3eb35e4d14893e9de4c3f590f014eed589369ff6397


build:
  number: 0


requirements:
  build:
    - {{ compiler('cxx') }}
    - {{ cdt('mesa-libgl-devel') }}                # [linux]
    - {{ cdt('mesa-dri-drivers') }}                # [linux]
    - {{ cdt('libselinux') }}                      # [linux]
    - {{ cdt('libxdamage') }}                      # [linux]
    - {{ cdt('libxxf86vm') }}                      # [linux]
    - git
    - conan
    - cmake
    - ninja
    - python
    - numpy

  host:
    - python
    - numpy
    - boost-cpp
    - hdf5
    - libgdal
    - pybind11
    - fmt
    - xorg-libxfixes                               # [linux]
    - glew
    - docopt.cpp
    - nlohmann_json
    - glfw
    - libhwloc
    - gperftools
    - asio

  run:
    - python
    - {{ pin_compatible('numpy') }}
    - hdf5
    - libgdal
    - fmt
    - docopt.cpp
    - glfw
    - gperftools


test:
    commands:
       - lue_translate -h
       - lue_validate -h
       - lue_view -h


about:
  home: https://lue.computationalgeography.org/
  license: MIT
  license_file: LICENSE.txt
  summary: 'Scientific database and environmental modelling framework.'
  description: |
    The LUE Python package allows you to perform I/O to the LUE Scientific Database,
    which is an HDF5 binary data format.

    The LUE database lets you efficiently store huge amounts of attribute values of
    huge amounts of objects. These objects can be located in time and/or in space,
    and the attribute values can be n-dimensional values. The LUE database is developed
    to be useful in the domain of agent-based and field-based modeling.

    The LUE Python package is currently in development.
  doc_url: https://lue.computationalgeography.org/doc/
  dev_url: https://github.com/computationalgeography/lue/


extra:
  recipe-maintainers:
    - OliverSchmitz
    - kordejong
