{% set version = "0.3.10" %}


package:
  name: lue
  version: {{ version }}

source:
  url: https://lue.computationalgeography.org/download/lue-{{ version }}.tar.bz2
  sha256: a8e998e46f4b9ce39bde965d328ed24f6672c9a238802a30ed24353e9534aa0a

build:
  number: 0
  skip: true  # [py<310 or (osx and x86_64)]

requirements:
  build:
    - {{ compiler("c") }}
    - {{ compiler("cxx") }}
    - {{ stdlib("c") }}
    - cmake
    - ninja
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - python                                 # [build_platform != target_platform]
    - numpy                                  # [build_platform != target_platform]

  host:
    - cxxopts
    - docopt  # templatize.py
    - hpx
    - jinja2  # templatize.py
    - libboost-devel
    - libgdal
    - nlohmann_json
    - numpy
    - pybind11
    - python

  run:
    # Packages needed for downstream packages that use LUE at:
    # - build-time: headers, libraries
    # - runtime: shared libraries, interpreter
    # Only list packages whose meta.yaml doesn't contain a run_exports already
    - docopt  # lue.qa
    - matplotlib-base  # lue.qa
    - python-dateutil  # lue.qa

test:
  imports:
    - lue
    - lue.data_model
    - lue.framework
    - lue.pcraster
    - lue.qa.scalability
  commands:
    - lue_translate -h
    - lue_validate -h
    - lue_calculate.py -h
    - lue_scalability.py -h

about:
  home: https://lue.computationalgeography.org/
  license: MIT
  license_file: LICENSE.txt
  summary: LUE scientific database and environmental modelling framework.
  description: |
    LUE is software supporting the representation and numerical simulation of geographical
    systems. Using LUE, model developers can develop models using a syntax that looks very
    similar to map algebra, in either Python or C++. Given such a model, modellers can simulate
    real-world geographical systems with a large extent and at high resolutions. LUE models
    can be executed on small laptops and on large cluster partitions.

    LUE is the result of multiple research projects performed by the Computational Geography
    group at Utrecht University in the Netherlands. One of the focus areas of this group is
    to improve on the concepts and design of numerical simulation frameworks for geographical
    systems, with respect to their functionality and performance.

    LUE supports both agent-based and field-based modelling of geographical systems, with the
    support for field-based modelling currently being the most mature.
  doc_url: https://lue.computationalgeography.org/doc/
  dev_url: https://github.com/computationalgeography/lue/

extra:
  recipe-maintainers:
    - kordejong
    - oliverschmitz
