{% set version = "0.2.0" %}


package:
  name: lue
  version: {{ version }}


source:
  url: http://pcraster.geo.uu.nl/pcraster/packages/src/lue-{{ version }}.tar.bz2
  sha256: cf073b3786a87c9f1677d362726f6994b1aaafc35192c6ea88ebd75ee16f35d7


build:
  number: 14

  ignore_run_exports:
    - fmt

requirements:
  build:
    - {{ compiler('cxx') }}
    - {{ cdt('mesa-libgl-devel') }}                # [linux]
    - {{ cdt('mesa-dri-drivers') }}                # [linux]
    - {{ cdt('libselinux') }}                      # [linux]
    - {{ cdt('libxdamage') }}                      # [linux]
    - {{ cdt('libxxf86vm') }}                      # [linux]
    - conan
    - cmake
    - ninja

  host:
    - python
    - numpy >=1.16
    - boost-cpp
    - hdf5
    - libgdal
    - sdl2
    - fmt
    - xorg-libxfixes                               # [linux]
    - glew

  run:
    - python
    - {{ pin_compatible('numpy') }}
    - boost-cpp
    - hdf5
    - libgdal
    - sdl2
    - fmt


test:
    commands:
       - lue_translate -h
       - lue_validate -h


about:
  home: https://lue.computationalgeography.org/
  license: MIT
  license_file: LICENSE.txt
  summary: Scientific database and environmental modelling framework.
  description: |
    The LUE Python package allows you to perform I/O to the LUE Scientific Database,
    which is an HDF5 binary data format.

    The LUE database lets you efficiently store huge amounts of attribute values of
    huge amounts of objects. These objects can be located in time and/or in space,
    and the attribute values can be n-dimensional values. The LUE database is developed
    to be useful in the domain of agent-based and field-based modeling.

    The LUE Python package is currently in development.
  doc_url: https://lue.computationalgeography.org/doc/
  dev_url: https://github.com/computationalgeography/lue.git


extra:
  recipe-maintainers:
    - OliverSchmitz
    - kordejong
