{% set version = "0.3.6" %}


package:
  name: lue
  version: {{ version }}


source:
  url: https://pcraster.geo.uu.nl/pcraster/packages/src/lue-{{ version }}.tar.bz2
  sha256: cf9b6caf61a7f286fc473f04045de2eaeae09b05455a34262c97d109b45ef82c


build:
  number: 0


requirements:
  build:
    # Section for the native build platform. Think "build-tools", that run on the native platform,
    # but output results for the target platform.
    # Dependencies required during the build phase not needed on the host.
    - python                                     # [build_platform != target_platform]
    - cross-python_{{ target_platform }}         # [build_platform != target_platform]
    - numpy >1.17                                # [build_platform != target_platform]
    - pybind11                                   # [build_platform != target_platform]
    - {{ compiler('cxx') }}
    - make                                       # [unix]
    - git
    - conan
    - cmake
    - ninja

  host:
    # Section for the target platform. Might not be the same as the build platform!
    # Dependencies required during build phase needed on the host.
    - python
    - numpy >1.17
    - boost-cpp
    - hdf5
    - hpx
    - libgdal
    - pybind11
    - fmt
    - docopt.cpp
    - nlohmann_json

  run:
    # Dependencies required for using the software.
    # Stuff required when using LUE.
    - python
    - {{ pin_compatible('numpy') }}
    - hdf5
    - hpx
    - libgdal
    - fmt
    - docopt.cpp


test:
  commands:
    - lue_translate -h
    - lue_validate -h


about:
  home: https://lue.computationalgeography.org/
  license: MIT
  license_file: LICENSE.txt
  summary: LUE scientific database and environmental modelling framework.
  description: |
    LUE is software supporting the representation and numerical simulation of geographical
    systems. Using LUE, model developers can develop models using a syntax that looks very
    similar to map algebra, in either Python or C++. Given such a model, modellers can simulate
    real-world geographical systems with a large extent and at high resolutions. LUE models
    can be executed on small laptops and on large cluster partitions.

    LUE is the result of multiple research projects performed by the Computational Geography
    group at Utrecht University in the Netherlands. One of the focus areas of this group is
    to improve on the concepts and design of numerical simulation frameworks for geographical
    systems, with respect to their functionality and performance.

    LUE support both agent-based and field-based modelling of geographical systems, with the
    support for field-based modelling currently being the most mature.
  doc_url: https://lue.computationalgeography.org/doc/
  dev_url: https://github.com/computationalgeography/lue/


extra:
  recipe-maintainers:
    - kordejong
    - oliverschmitz
